# Change these first
owner: zowievangeest # Your GitHub username
repo: voorhoede-support-upptime # Your Github repository name

# Add your sites here
sites:
  - name: Voorhoede
    url: https://www.voorhoede.nl/nl/
  - name: Voorhoede Support
    url: https://support.voorhoede.nl

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /voorhoede-support-upptime
  logoUrl: https://www.voorhoede.nl/images/logo-with-text.svg
  name: Voorhoede Support Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Voorhoede Support Upptime
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
