# Change these first
owner: zowievangeest # Your GitHub username
repo: voorhoede-support-upptime # Your Github repository name

# Add your sites here
sites:
  - name: Voorhoede
    url: https://www.voorhoede.nl/nl/
  - name: Voorhoede Support
    url: https://support.voorhoede.nl

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /voorhoede-support-upptime
  logoUrl: https://www.voorhoede.nl/images/logo-with-text.svg
  name: uptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This website shows the uptime statistics of all websites that are maintained in our [support portal](https://support.voorhoede.nl)
  navbar:
    - title: uptime
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
